# Generated by Django 5.2.1 on 2025-06-23 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('c#', 'C#')])),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('sn', 'Senior'), ('md', 'Middle'), ('jn', 'Junior'), ('tl', 'TeamLead')])),
                ('projects', models.ManyToManyField(blank=True, null=True, related_name='devs', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('db_backend', 'Backend'), ('db_frontend', 'Frontend'), ('db_q&a', 'Q&A'), ('db_design', 'Design'), ('db_devops', 'DevOps')], max_length=50, unique=True)),
                ('projects', models.ManyToManyField(blank=True, null=True, related_name='tags', to='project.project')),
            ],
        ),
    ]
